# Generated by Django 4.0 on 2023-04-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, db_column='Color', max_length=30, null=True)),
            ],
            options={
                'db_table': 'colors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, db_column='Type', max_length=30, null=True)),
            ],
            options={
                'db_table': 'types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(blank=True, db_column='TName', max_length=30)),
                ('descr', models.CharField(blank=True, db_column='Descr', max_length=255, null=True)),
                ('dateTask', models.DateTimeField(db_column='DateTask')),
                ('datenotif', models.DateTimeField(db_column='DateNotif')),
                ('reminder', models.BooleanField(db_column='Reminder')),
                ('flag', models.BooleanField(db_column='Flag')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalendarApp.colors')),
                ('type', models.ForeignKey(db_column='Type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='CalendarApp.types')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'tasks',
                'managed': True,
            },
        ),
    ]
