# Generated by Django 4.0 on 2023-05-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField()),
            ],
            options={
                'ordering': ['flag'],
            },
        ),
    ]
